export const countryList = [
    {
        name:'pakistan',
        code:'15000',
        cities: [
           "Karachi" ,
            "Lahore",
            "Kotla Qasim Khan",
            "Faisalabad",
            "Rawalpindi",
            "Gujranwala",
            "Peshawar",
            "Multan",
            "Hyderabad City",
            "Islamabad",
            "Quetta",
            "Cantonment",
            "Eminabad",
            
        ],
    },
    {
      name: 'Singapore',
      code: 'SG',
      cities: [
        "Ang Mo Kio New Town",
        "Ayer Raja New Town",
        "Bedok New Town",
        "Boon Lay",
        "Bukit Batok New Town",
        "Bukit Panjang New Town",
        "Bukit Timah",
        "Bukit Timah Estate",
        "Changi Village",
        "Choa Chu Kang New Town",
        "Clementi New Town",
        "Holland Village",
        "Hougang",
        "Jurong East New Town",
        "Jurong Town",
        "Jurong West New Town",
        "Kalang",
        "Kampong Pasir Ris",
        "Kembangan",
        "Pandan Valley",
        "Pasir Panjang",
        "Punggol",
        "Queenstown Estate",
        "Serangoon",
        "Simei New Town",
        "Singapore",
        "Tai Seng",
        "Tampines New Town",
        "Tanglin Halt",
        "Tanjong Pagar",
        "Toa Payoh New Town",
        "Woodlands New Town",
        "Yew Tee",
        "Yishun New Town",
      ],
    },
    {
      name: 'Bahrain',
      code: 'BH',
      cities: [
        "Al Budayyi`",
        "Al Hadd",
        "Al Hamalah",
        "Al Janabiyah",
        "Al Markh",
        "Al Muharraq",
        "Bani Jamrah",
        "Barbar",
        "Jurdab",
        "Madinat `Isa",
        "Madinat Hamad",
        "Manama",
        "Oil City",
        "Sanabis",
        "Sanad",
        "Sitrah",
        "Tubli",
      ],
    },
  ];

 